### ISSUE TITLE
It is not working

### ISSUE THREAD

**Issue by yarodevuci** [wjur/sym-diff-prolog#1]
Simple test case deriv(x^5, L).

**Comment by wjur** [comment]
It's because you used an incorrect command - it's `diff` not `deriv`, @yarodevuci.  Also, you forgot to specify the variable name.
```prolog
?- diff(x^5, x, L).
L = x^4*5 
```

**Comment by yarodevuci** [comment]
@wjur Is it possible to do without to mention the variable? so it will be only 2 params?

**Comment by wjur** [comment]
It is possible. Just define another predicate that supplies 'x' as the second parameter.
```prolog
diff2(F, FF) :-
    diff(F, x, FF). 
```
Then, you can use it like this:
```prolog
?- diff2(x*2, Y).
Y = 2 
```

Does this answer your question?

**Comment by yarodevuci** [comment]
@wjur Excellent. Thank you
