### ISSUE TITLE
Bad output 

### ISSUE THREAD

**Issue by yarodevuci** [wjur/sym-diff-prolog#2]
deriv((x*2*x)/x, Y). should return 2
Instead I am getting Y = ((2*x+x*2)*x-x*2*x)/(x*x) .which is same as 2 but that's bad answer ..

**Comment by wjur** [comment]
I really want to help you, @yarodevuci, but I'm not exactly sure what you're trying to do. Take a look at your issue #1 from a year ago. It's not deriv, but diff.  The syntax you're using is not supported. Are you sure you're using my code?

**Comment by yarodevuci** [comment]
Hi @wjur I am just trying to say your code needs simplification rules.

**Comment by wjur** [comment]
@yarodevuci, at the time of writing, I was fine with basic simplifications because that was the requirements of the project. I wasn't planning to extend the project beyond the initial requirements, but if you want to contribute with a PR I can help you with it.

**Comment by wjur** [comment]
@yarodevuci take a look at https://github.com/christian-vigh/prolog-experiments/blob/master/External%20Sources/Sources/algebra/simpsv.pro as it contains symbolic simplification of algebraic functions.
